import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {CASH_SITES} from '../cash-dash-state.js';
const url=new URL('../server/worker.js',import.meta.url);
let source=await readFile(url,'utf8');
source=source.replace("import {DurableObject} from 'cloudflare:workers';",'class DurableObject {}');
source=source.replace(/from '([^']+)'/g,(all,path)=>path.startsWith('.')?`from '${new URL(path,url).href}'`:all);
const {IslandRoom}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
test('worker accepts Ishi start in companion mode and validates Moshi pickup proximity',async()=>{
  const room=Object.create(IslandRoom.prototype),messages=[];
  const now=Date.now(),ishi={user:'ISHIEE',lastSeen:now,lastPose:now},moshi={user:'MOSHIEE',lastSeen:now,lastPose:now};
  const i={serializeAttachment(){}},m={serializeAttachment(){}};
  room.sockets=new Map([[i,ishi],[m,moshi]]);
  room.data={world:{candles:true},poses:{MOSHIEE:{position:[CASH_SITES[0].x,2,CASH_SITES[0].z],lying:false}}};
  room.save=()=>{};room.broadcast=message=>messages.push(message);
  room.snapshot=()=>({world:room.data.world});
  const send=(ws,event)=>room.webSocketMessage(ws,JSON.stringify({type:'event',event}));
  await send(m,{type:'cash-start'});assert.equal(room.data.world.cashDash,undefined);
  await send(i,{type:'cash-start'});assert.ok(room.data.world.cashDash);
  room.data.world.cashDash.startAt=now-1000;room.data.world.cashDash.endAt=now+30000;
  await send(i,{type:'cash-pickup',index:0});assert.deepEqual(room.data.world.cashDash.collected,[]);
  await send(m,{type:'cash-pickup',index:39});assert.deepEqual(room.data.world.cashDash.collected,[]);
  await send(m,{type:'cash-pickup',index:0});assert.deepEqual(room.data.world.cashDash.collected,[0]);
  await send(m,{type:'cash-pickup',index:0});assert.equal(messages.length,2);
  room.data.world.cashDash.endAt=now-1;
  await send(m,{type:'cash-pickup',index:1});assert.deepEqual(room.data.world.cashDash.collected,[0]);
  await send(i,{type:'mood',value:'sunset'});assert.equal(room.data.world.mood,'sunset');
  room.data.poses.ISHIEE={position:[-7,2,-4],yaw:0};
  await send(i,{type:'fireworks',amount:7});
  assert.equal(messages.at(-1).event.type,'fireworks');
  assert.deepEqual(messages.at(-1).event.pose,room.data.poses.ISHIEE,'companion host uses his server-owned pose');
  room.data.world.candles=false;
  await send(i,{type:'candles'});assert.equal(room.data.world.candles,false,'orchestration does not grant control of her interactions');
});
