"""Non-destructive variant: lengthen and relax only the lower rear hair."""
import bpy,json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
source=(root/'assets/reference-hair.js').read_text()
data=json.loads(source.split('export const hairMesh=',1)[1].strip().rstrip(';'))
bpy.ops.wm.read_factory_settings(use_empty=True)
def smooth(t):
    t=max(0,min(1,t));return t*t*(3-2*t)
verts=[];weights=[]
for i in range(0,len(data['positions']),3):
    x,y,z=data['positions'][i:i+3]
    lower=smooth((1.49-y)/.39);rear=smooth((z-.015)/.17)
    weight=lower*rear;weights.append(weight)
    y-=.09*weight;z+=.05*weight
    verts.append((x,-z,y))
faces=[data['indices'][i:i+3] for i in range(0,len(data['indices']),3)]
mesh=bpy.data.meshes.new('Relaxed rear hair');mesh.from_pydata(verts,[],faces);mesh.update()
obj=bpy.data.objects.new('Longer gently curved back',mesh);bpy.context.collection.objects.link(obj)
bpy.context.view_layer.objects.active=obj;obj.select_set(True)
group=obj.vertex_groups.new(name='Lower back only')
for i,w in enumerate(weights):
    if w>0:group.add([i],w,'REPLACE')
mod=obj.modifiers.new('Soften lower back waves','SMOOTH');mod.factor=.55;mod.iterations=5;mod.vertex_group=group.name
bpy.ops.object.modifier_apply(modifier=mod.name)
for face in mesh.polygons:face.use_smooth=True
mesh.update();mesh.calc_loop_triangles()
positions=[];normals=[]
for v in mesh.vertices:
    positions.extend(round(a,6) for a in (v.co.x,v.co.z,-v.co.y))
    normals.extend(round(a,6) for a in (v.normal.x,v.normal.z,-v.normal.y))
indices=[i for t in mesh.loop_triangles for i in t.vertices]
(root/'assets/reference-hair-relaxed.js').write_text('// Variant of reference-hair.js; generated by modeling/relax-back-hair.py.\nexport const hairMesh='+json.dumps(dict(positions=positions,normals=normals,indices=indices),separators=(',',':'))+';\n')
bpy.ops.wm.save_as_mainfile(filepath=str(root/'assets/reference-hair-relaxed.blend'))
print('RELAXED_HAIR',len(mesh.vertices),len(indices)//3,'unchanged-front vertices',sum(w==0 for w in weights))
